package Bmj.panels;

import static Bmj.panels.ManageMotor.refreshDataMotor;
import Bmj.util.Koneksi;
import Bmj.util.Motor;
import Bmj.util.Pegawai;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author Adies
 */
public class Transaksi extends javax.swing.JPanel {

    Motor Dm;
    Pegawai P;

    /**
     * Creates new form FORMTRANSAKSI
     */
    public Transaksi() {
        initComponents();
        otomatisKodeTransaksi();
        refreshDataMotor("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        srcMotor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        srcJumlah = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        inpKode = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        inpTotal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        inpBayar = new javax.swing.JTextField();
        inpKembalian = new javax.swing.JTextField();
        btnNew = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Form Transaksi");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Masukkan Nama Barang");

        srcMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srcMotorActionPerformed(evt);
            }
        });
        srcMotor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                srcMotorKeyReleased(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id_motor", "merk", "tipe", "tahun", "warna", "harga", "stok"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(6).setHeaderValue("stok");
        }

        srcJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srcJumlahActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Jumlah");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Tambahkan");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id_transaksi", "nama_pegawai", "id_pelanggan", "tanggal", "total_harga", "pembayaran"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Kode Transaksi");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Data Barang");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Total");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Bayar");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Kembalian");

        btnNew.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNew.setText("New");

        btnHapus.setText("-");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Hapus");

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(srcMotor))
                                        .addGap(18, 18, 18)
                                        .addComponent(btnRefresh))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel3)
                                            .addComponent(srcJumlah, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(37, 37, 37)
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(inpKode, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel7))
                                .addGap(170, 596, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(inpTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                    .addComponent(inpBayar))
                                .addGap(16, 16, 16)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(inpKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNew)
                                .addGap(142, 142, 142)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnHapus))
                            .addComponent(jLabel11))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(srcMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(srcJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(inpKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(inpTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inpBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(inpKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void srcMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srcMotorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_srcMotorActionPerformed

    private void srcJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srcJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_srcJumlahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int n = jTable1.getSelectedRow();
        if (n != -1) {
            //ekstraksi data
            Dm = new Motor();
            String IDmtr = jTable1.getValueAt(n, 0).toString();
            int ID = Integer.valueOf(IDmtr);
            String merk = jTable1.getValueAt(n, 1).toString();
            String tipe = jTable1.getValueAt(n, 2).toString();
            String tahun = jTable1.getValueAt(n, 3).toString();
            String warna = jTable1.getValueAt(n, 4).toString();
            String harga = jTable1.getValueAt(n, 5).toString();
            String stok = jTable1.getValueAt(n, 6).toString();
            Dm.setId_motor(ID);
            Dm.setMerk(merk);
            Dm.setTipe(tipe);
            Dm.setTahun(tahun);
            Dm.setWarna(warna);
            Dm.setHarga(harga);
            Dm.setStok(stok);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void srcMotorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_srcMotorKeyReleased
        searchDataMotor();
    }//GEN-LAST:event_srcMotorKeyReleased

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        jTable1.clearSelection();
        refreshDataMotor("");
        srcMotor.setText("");
        srcJumlah.setText("");
        inpKode.setText("");
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int barisAtas = jTable1.getSelectedRow();
        if (barisAtas == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih motor dulu di tabel atas!");
            return;
        }

        if (srcJumlah.getText().equals("")) { // srcJumlah sesuaikan dengan nama variabelmu
            javax.swing.JOptionPane.showMessageDialog(this, "Isi jumlah barang!");
            return;
        }
        String id_transaksi = inpKode.getText();
        String namaPegawai = "Admin";
        String idPelanggan = "PLG-" + (new java.util.Random().nextInt(9000) + 1000);

        String merk = jTable1.getValueAt(barisAtas, 1).toString();

        // Ambil Harga dari Tabel Atas (Kolom ke-5 / indeks 5)
        String hargaStr = jTable1.getValueAt(barisAtas, 5).toString();
        // Bersihkan titik/koma (misal 15.000.000 jadi 15000000)
        long harga = Long.parseLong(hargaStr.replace(".", "").replace(",", ""));
        int jumlah = Integer.parseInt(srcJumlah.getText());
        long total_harga = harga * jumlah;

        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable2.getModel();

        model.addRow(new Object[]{
            id_transaksi,
            namaPegawai,
            idPelanggan,
            merk,
            harga,
            jumlah,
            total_harga
        });
        hitungTotalBelanja();

        try {
            // Ambil angka dari kode sekarang (misal "TRX001" diambil "001")
            // Asumsi formatnya selalu 3 huruf depan diikuti angka
            // Ambil teksnya dulu (.getText()), baru dipotong (.substring)
            String angkaSaja = inpKode.getText().substring(3);
            int urutanBaru = Integer.parseInt(angkaSaja) + 1;

            // Format balik menjadi TRX + 3 digit angka (misal TRX002)
            String kodeBaru = "TRX" + String.format("%03d", urutanBaru);

            // Pasang kode baru ke textfield agar siap untuk barang berikutnya
            inpKode.setText(kodeBaru);

        } catch (Exception e) {
            // Jika format kode kamu bukan TRX... (misal manual ketik "aa1")
            // Maka biarkan saja, atau buat logika lain.
            System.out.println("Gagal auto increment kode: " + e.getMessage());
        }

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JTextField inpBayar;
    private javax.swing.JTextField inpKembalian;
    private javax.swing.JTextField inpKode;
    private javax.swing.JTextField inpTotal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JTable jTable1;
    private static javax.swing.JTable jTable2;
    private javax.swing.JTextField srcJumlah;
    private javax.swing.JTextField srcMotor;
    // End of variables declaration//GEN-END:variables

    public static void refreshDataMotor(String w) {
        try {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            for (int i = model.getRowCount() - 1; i >= 0; i--) {
                model.removeRow(i);
            }

            Connection K = Koneksi.Go();
            String Q = "SELECT * FROM tabel_motor" + w;
            Statement S = K.createStatement();
            ResultSet R = S.executeQuery(Q);
            while (R.next()) {
                int id = R.getInt("id_motor");
                String merk = R.getString("merk");
                String tipe = R.getString("tipe");
                String tahun = R.getString("tahun");
                String warna = R.getString("warna");
                String harga = R.getString("harga");
                String stok = R.getString("stok");
                Object[] datamotor = {id, merk, tipe, tahun, warna, harga, stok};
                model.addRow(datamotor);
            }

        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());

        }
    }

    private void searchDataMotor() {
        String key = srcMotor.getText();
        String where = " WHERE "
                + "id_motor LIKE '%" + key + "%' OR "
                + "merk LIKE '%" + key + "%' OR "
                + "tipe LIKE '%" + key + "%' OR "
                + "tahun LIKE '%" + key + "%' OR "
                + "warna LIKE '%" + key + "%' OR "
                + "harga LIKE '%" + key + "%' OR "
                + "stok LIKE '%" + key + "%'";
        refreshDataMotor(where);
    }

    // Method untuk membuat Kode Transaksi Otomatis (Contoh: TRX001)
    private void otomatisKodeTransaksi() {
        try {
            java.sql.Connection conn = (java.sql.Connection) Bmj.util.Koneksi.Go();
            java.sql.Statement stm = conn.createStatement();

            // Ambil id_transaksi terakhir, urutkan dari yang terbesar
            String sql = "SELECT id_transaksi FROM transaksi ORDER BY id_transaksi DESC LIMIT 1";
            java.sql.ResultSet res = stm.executeQuery(sql);

            if (res.next()) {
                String id = res.getString("id_transaksi");
                // Misal format ID di database adalah "TRX001"
                // Kita ambil angkanya saja (mulai indeks ke-3)
                int nomor = Integer.parseInt(id.substring(3)) + 1;

                // Format ulang menjadi TRX + 3 digit angka (001, 002, dst)
                String kodeBaru = "TRX" + String.format("%03d", nomor);
                inpKode.setText(kodeBaru); // Pastikan nama variabel textfield kamu sesuai
            } else {
                // Jika belum ada data sama sekali
                inpKode.setText("TRX001");
            }
        } catch (Exception e) {
            System.out.println("Error Kode Otomatis: " + e.getMessage());
            // Fallback jika error
            inpKode.setText("TRX001");
        }
    }

    private void hitungTotalBelanja() {
        int total = 0;
        for (int i = 0; i < jTable2.getRowCount(); i++) {
            // Ambil angka dari kolom Subtotal (misal kolom index 3)
            int sub = Integer.parseInt(jTable2.getValueAt(i, 3).toString());
            total += sub;
        }
        inpTotal.setText(String.valueOf(total)); // txtTotal adalah nama field Total di bawah
    }

}
